### ISSUE TITLE
'keyRepoPasswordPtr' undeclared

### ISSUE THREAD

**Issue by ouwe-knutselaar** [ibm-messaging/mq-golang#189] opened 2022-07-07 07:00 UTC
L.S.

I get the following error:
`C:\Users\userid\go\pkg\mod\github.com\ibm-messaging\mq-golang\v5@v5.3.0\ibmmq\mqiMQSCO.go: In function`
`'setScoKeyRepoPassword':  `
`C:\Users\userid\go\pkg\mod\github.com\ibm-messaging\mq-golang\v5@v5.3.0\ibmmq\mqiMQSCO.go:41:7: error:   `
`'keyRepoPasswordPtr' undeclared (first use in this function); did you mean 'keyRepoPassword'?  `
`   if (keyRepoPasswordPtr != NULL) {   `
`       ^~~~~~~~~~~~~~~~~~`
`       keyRepoPassword`
`C:\Users\userid\go\pkg\mod\github.com\ibm-messaging\mq-golang\v5@v5.3.0\ibmmq\mqiMQSCO.go:41:7: note: each undeclared identifier is reported only once for each function it appears in`

And this is the code is use:

`cno := ibmmq.NewMQCNO()   `
`cno.Options = ibmmq.MQCNO_CLIENT_BINDING   `
`qMgrObject, err := ibmmq.Conn(qMgrName,cno)`

What is missing?

Erwin

**Comment by ibmmqmet** [comment] 2022-07-07 10:14
Sorry about that. Caused by same late-breaking name changes. Should be fixed in 5.3.1 that I just pushed

**Closed** 2022-07-18 05:54 UTC
