### ISSUE TITLE
Feature Request: Ability to display channel and queue manager statistics

### ISSUE THREAD

**Issue by stevengonsalvez** [ibm-messaging/mq-golang#19] opened 2017-09-20 08:16 UTC
The statistics integrated into prometheus is really lovely and is a good replacement as a open monitoring system. 
It would be really good , if we could source channel statistics, Message Ages (on queues), queue manager and SSL statistics.

**Comment by ibmmqmet** [comment] 2017-09-20 17:06
I can imagine having something equivalent to amqsmon that processes the statistics information (via STATQMGR, STATCHL, STATMQI attributes etc), even though 
a) that is not delivered via pub/sub so could interfere with other monitors unless steps are taken ...
b) the qmgr and queue data in those events are near-duplicate of the current published stats
c) is not automatically enabled on qmgrs, and has to be turned on.
Perhaps do something that optionally enables the attributes, and perhaps only for channels rather than the other supported resources.

I think it's unlikely this package would be extended to handle data from the QSTATUS or CHLSTATUS output. While it is of course possible, many of the fields returned there are not metrics in the same sense, so would not fit as neatly into a prometheus DB. Maybe something for a different package, and/or a different database storage model.

I've no plans to extend this right now anyway, but will consider it for any future updates.

**Closed by ibmmqmet** 2017-09-20 17:06 UTC
